server:
  port: 8080
  servlet:
    context-path: /

spring:
  redis:
    host: 127.0.0.1
    password: redis
    port: 6379
    database: 0
    jedis:
      pool:
        max-active: 100
        # 连接池最大阻塞等待时间,-1表示没有限制
        max-wait: -1ms
        min-idle: 10
        max-idle: 20
    # 连接超时 ms
    timeout: 1000ms
  # 分布式session存储方式
  session:
    store-type: redis