server:
  port: 8080
  servlet:
    context-path: /

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    password: zhanghang
    url: jdbc:mysql://127.0.0.1:3306/website?characterEncoding=UTF-8&serverTimezone=GMT
    dbcp2:
      pool-prepared-statements: true
      max-open-prepared-statements: 20
      validation-query: select 'x'
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
    # 合并多个DruidDataSource的监控数据
    useGlobalDataSourceStat: true
    # 开始mergeSql，慢SQL
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
    # 配置监控统计拦截的filters，去掉后监控界面的sql无法统计
    filters: stat,wall
    # 开启PSCache
    poolPreparedStatements: false

mybatis:
  mapperLocations: classpath:mapper/*.xml
  typeAliasesPackage: com.github.entity
  config-location: classpath:mybatis-config.xml