server:
  port: 8080
  servlet:
    context-path: /
spring:
  thymeleaf:
    suffix: .html
    mode: HTML
    cache: false
    encoding: UTF-8
    check-template-location: true
    prefix: classpath:/templates/
